[package]
edition = "2021"
name = "modhook"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "libmodhook"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
detours-sys = {version = "0.1.2"}
widestring = "1.0.2"
winapi = {version = "0.3.9", features = ["winbase", "handleapi", "minwindef", "consoleapi", "winnt", "memoryapi", "namedpipeapi"]}

[build-dependencies]
asar = "0.2.0"
