[package]
edition = "2021"
name = "discord_modloader"
version = "2.0.0-beta1"

[lib]
crate-type = ["cdylib", "lib"]
name = "discord_modloader"

[dependencies]
asar = "0.3.0"
clap = { version = "4.5.20", features = ["derive"] }
dirs = "5.0.1"
serde = { version = "1.0.210", features = ["serde_derive"] }
toml = "0.8.19"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = [
    "winbase",
    "handleapi",
    "minwindef",
    "consoleapi",
    "winnt",
    "memoryapi",
    "namedpipeapi",
] }
dll-syringe = "0.15.2"
detours-sys = { version = "0.1.2" }
widestring = "1.1.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2.166"
retour = { version = "0.3.1", features = ["static-detour"] }

[build-dependencies]
asar = "0.3.0"
