[mod]
name = "moonlight"
path = "/path/to/moonlight/dist"
entrypoint = "injector.js"
icon = "moonlight.png"

[mod.loader]
require = """
require("__MOD_ENTRYPOINT_FILE__").inject(
    require("path").resolve(__dirname, "../_app.asar")
);
"""
