name: Package examples

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - "./**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package:
    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest] # no macos-latest yet

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo +nightly install cargo-packager --locked
      - run: cargo +nightly release
