name: Publish

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package:
    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest] # no macos-latest yet

    runs-on: ${{ matrix.platform }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo +nightly install cargo-packager --locked
      - run: cargo +nightly release
  
  release:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/discord-modloader_*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          draft: true
          prerelease: ${{ contains(github.ref, 'beta') }}
